### ISSUE TITLE
Lien page de démonstration 

### ISSUE THREAD

**Issue by benchti** [access42/AccessTooltip#8]
Les 2 liens de démonstration du Readme https://github.com/access42/AccessTooltip/blob/master/README.md sont ko 
- http://access42.github.io/AccessTooltip/en 
- http://access42.github.io/AccessTooltip/

**Comment by audreymaniez** [comment]
Merci !  une erreur de manipulation sans doute.
C'est rétabli maintenant.
Merci de l'avoir notifié.
